version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@salte-auth/salte-auth"
    versions:
    - "^3.0.0"
  - dependency-name: sinon
    versions:
    - "> 9"
