extends: google
env:
  browser: true
  jasmine: true
globals:
  angular: true
rules:
  max-nested-callbacks: 0
  no-warning-comments: 0
  require-jsdoc: 0
  camelcase: 0
  max-len: 0
  object-curly-spacing: 0
  one-var: 0
  arrow-parens: 0
  new-cap: 0
  no-trailing-spaces: 0
  no-negated-condition: 0
